import localFont from "next/font/local";
import "./globals.css";
// import "@uploadthing/react/styles.css";
import { Toaster } from "@/components/ui/toaster";
import NavbarWrapper from "@/components/navbar";
import { AuthProvider } from "@/providers/auth";

const balooFont = localFont({
  src: [
    {
      path: "./fonts/baloo-n.ttf",
      weight: "400",
      style: "normal",
    },

    {
      path: "./fonts/baloo2.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata = {
  title: "Bug Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${balooFont.className} antialiased`}>
        <AuthProvider>
          <NavbarWrapper>
            {children}
            <Toaster />
          </NavbarWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
