import localFont from "next/font/local";
import "./globals.css";
// import "@uploadthing/react/styles.css";

import NavbarWrapper from "@/components/navbar";
import { ReactQueryClientProvider } from "@/providers/react-query";
import { AuthProvider } from "@/providers/auth";


const balooFont = localFont({
  src: "./fonts/baloo2.woff",
  variable: "--font-baloo-font",
  weight: "100 900",
})


export const metadata = {
  title: "Bug Bank",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${balooFont.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <AuthProvider>
            <NavbarWrapper>{children}</NavbarWrapper>
          </AuthProvider>
        </ReactQueryClientProvider>
       
      </body>
    </html>
  );
}
